### ISSUE TITLE
how to integrate?

### ISSUE THREAD

**Issue by septs** [riobard/go-shadowsocks2#1]
I want to use to replace the use `shadowsocks-go`.

**Comment by riobard** [comment]
Could you please elaborate on what is missing? You can use it to replace the old Go port right now.

**Comment by septs** [comment]
export [pickCipher](https://github.com/shadowsocks/go-shadowsocks2/blob/47512d9f9839d5769d855ccd93868da51f0435cf/cipher.go#L61-L91) function and [listCipher](https://github.com/shadowsocks/go-shadowsocks2/blob/47512d9f9839d5769d855ccd93868da51f0435cf/cipher.go#L48-L58) function

**Comment by riobard** [comment]
Those are two helper functions for the command line arguments. May I ask why you want them to be exported?

**Comment by septs** [comment]
this is the way to minimize changes to this project

by https://github.com/RouterScript/ProxyClient
see https://github.com/RouterScript/ProxyClient/blob/master/proxy_shadowsocks.go

**Comment by riobard** [comment]
I see. You want to import the entire Shadowsocks implementation as a whole and use it directly.

Currently this is not how the code is structured. `pickCipher` and `listCipher` are part of `package main` to build the executable. I need to think about if it's better to move them to `package cipher` or somewhere else.

**Comment by septs** [comment]
????

**Comment by riobard** [comment]
Please wait. This repo is not stable yet. We're working on finishing the design of the new AEAD cipher here https://github.com/shadowsocks/shadowsocks-org/issues/42

**Comment by septs** [comment]
can I lock the conversation?

**Comment by riobard** [comment]
Sure.
