### ISSUE TITLE
为什么不使用相对路径的import呢？

### ISSUE THREAD

**Issue by kuyapp** [riobard/go-shadowsocks2#10]
比如： https://github.com/riobard/go-shadowsocks2/blob/master/main.go#L17
fork的人需要改一遍import，但提PR时就会有点问题
找到了这个办法，但还是想知道不使用相对路径的import原因
http://stackoverflow.com/questions/14323872/using-forked-package-import-in-go

**Comment by riobard** [comment]
Relative import path is discouraged by Go team.
