### ISSUE TITLE
User shadowsocks android client to connect go-shadowsocks server

### ISSUE THREAD

**Issue by bradyjoestar** [riobard/go-shadowsocks2#12]
I wonder if we can user shadowsocks-android client to connect the go-shadowsocks server now?
If not,I want to try  to implement this feature, what should I do?:)

**Comment by riobard** [comment]
It should be compatible.

**Comment by bradyjoestar** [comment]
Thanks,and I will test it.

**Comment by bradyjoestar** [comment]
Sorry but when I use shadowsocks-android to connect the server,it mentoned that:
2017/06/21 19:00:26 failed to get target address: chacha20poly1305: message authentication failed
2017/06/21 19:00:26 failed to get target address: chacha20poly1305: message authentication failed

I serarch the "message authentication failed" in the source code and cannot get the location of it.
I can connect to the shadowsocks-libev by android application.

Is there any config that I ignore?

**Comment by riobard** [comment]
What's the list of available ciphers from the android client?

**Comment by bradyjoestar** [comment]
I upload the screenshop ang the image url is below:
http://chuantu.biz/t5/113/1498046203x3080560663.png

_Sent from my HUAWEI BTV-W09 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by riobard** [comment]
Choose `chacha20-ietf` on the client and server.

**Comment by bradyjoestar** [comment]
successed!Thanks a lot! 👍
