### ISSUE TITLE
TCP fast open support

### ISSUE THREAD

**Issue by ipfans** [riobard/go-shadowsocks2#14]
TCP fast open will help to use ss-protocol on Linux or OSX.

So I think should enable tcp fast open with parameters to accelerate network speed

**Comment by riobard** [comment]
TCP Fast Open requires support from Go core library, which was planned for Go 1.9 but didn't make it. Will have to wait for Go 1.10.

**Comment by ipfans** [comment]
I think we should keep it open until Go 1.10 release?

**Comment by riobard** [comment]
Will have to wait for this https://github.com/golang/go/issues/4842

**Comment by riobard** [comment]
Go won't have official support for TFO in the future. See https://github.com/golang/go/issues/4842#issuecomment-655270404
