### ISSUE TITLE
When I run the server side on android， it will be failed to lockup dns

### ISSUE THREAD

**Issue by leimiu** [riobard/go-shadowsocks2#16]
error log: 
```
error connecting to: clients4.google.com:443 dial tcp: lookup clients4.google.com on [::1]:53: read udp [::1]:45904->[::1]:53: read: connection refused
```

**Comment by riobard** [comment]
I don't have Android to test, but are you sure that you're running SS _server_ on Android???

**Comment by leimiu** [comment]
yes, i need to run it on android....

**Comment by qtopie** [comment]
I try to use Android client to connect, but failed with this message: `failed to get target address: SOCKS error: 8` ;  I can also repeat this error with [shadowsocks-go client](https://github.com/shadowsocks/shadowsocks-go/tree/master/cmd/shadowsocks-local)

**Comment by riobard** [comment]
@artificerpi Most likely because you used different cipher on the client.
