### ISSUE TITLE
Error: "too many colons in address" in windows 10

### ISSUE THREAD

**Issue by bjzhang** [riobard/go-shadowsocks2#28]
First of all, thanks for your work. I try this in Linux. It works in both client and server. But when I try to run the client in windows10. It says "too many colons in address". The command is as follows:
> shadowsocks2-win64.exe -c 'ss://AEAD_CHACHA20_POLY1305:bar@1.1.1.1:8488' -verbose -socks :1080 -u -udptun :8053=8.8.8.8:53,:8054=8.8.4.4:53 -tcptun :8053=8.8.8.8:53,:8054=8.8.4.4:53
2018/09/02 09:30:07 udp.go:81: UDP server address error: address 'ss://AEAD_CHACHA20_POLY1305:bar@1.1.1.1:8488': too many colons in address
2018/09/02 09:30:07 udp.go:27: UDP server address error: address 'ss://AEAD_CHACHA20_POLY1305:bar@1.1.1.1:8488': too many colons in address
2018/09/02 09:30:07 tcp.go:24: TCP tunnel :8054 <-> 'ss://AEAD_CHACHA20_POLY1305:bar@1.1.1.1:8488' <-> 8.8.4.4:53
2018/09/02 09:30:07 tcp.go:13: SOCKS proxy :1080 <-> 'ss://AEAD_CHACHA20_POLY1305:bar@1.1.1.1:8488'
2018/09/02 09:30:07 udp.go:27: UDP server address error: address 'ss://AEAD_CHACHA20_POLY1305:bar@1.1.1.1:8488': too many colons in address
2018/09/02 09:30:07 tcp.go:24: TCP tunnel :8053 <-> 'ss://AEAD_CHACHA20_POLY1305:bar@1.1.1.1:8488' <-> 8.8.8.8:53

If I change ss://AEAD_CHACHA20_POLY1305:bar@1.1.1.1:8488 to ss://AEAD_CHACHA20_POLY1305, there is no above error. So, I suppose there are some escape issues. But I am not familar with the escape characters in windows10. I am confusing after I read the [the following link](https://stackoverflow.com/questions/6828751/batch-character-escaping). And there is [similar issue](https://github.com/docker/machine/issues/3593) in docker in 2016. It still opens.

Thanks.

**Comment by riobard** [comment]
Seems like a Go problem, not specific to go-ss2. I don't use Windows so if anyone knows how to fix it, please send a pull request.

**Comment by bjzhang** [comment]
I avoid it by using Linux(ubuntu) on windows. Still hope someone could fix it.

**Comment by silverzhaojr** [comment]
Try double quote instead of single quote.

**Comment by riobard** [comment]
Try replace single quotes with double quotes.
