### ISSUE TITLE
能在服务端开启/禁止tunnel 吗？

### ISSUE THREAD

**Issue by josh-chan** [riobard/go-shadowsocks2#3]
今天试用时候不小心把服务器端 redis 数据给删除了。。。

**Comment by riobard** [comment]
😂

But it's not possible

**Comment by riobard** [comment]
Actually, this is a security flaw that should be fixed. Re-opening for consideration.

**Comment by ccsexyz** [comment]
可以考虑将一些地址设置为禁止连接

**Comment by riobard** [comment]
Right. There should be a blacklist to forbid connections to certain IP ranges and domains.

**Comment by riobard** [comment]
I think the security issues should be solved using Linux network namespace to isolate and firewall connections from the server process.
