### ISSUE TITLE
Does shadowsocks2 enable multi-user mode?

### ISSUE THREAD

**Issue by thex86guy** [riobard/go-shadowsocks2#35]
Apologies if this is the wrong place or the wrong question but I was wondering if `shadowsocks2` defends against attacks listed in https://github.com/shadowsocks/shadowsocks-org/issues/54? Specifically, I am curious if I can deploy an instance defending against these attacks with `shadowsocks2`?

**Comment by riobard** [comment]
Not yet.

**Comment by thex86guy** [comment]
OK thank you. Should I close this or is it fine to leave this open for tracking?

**Comment by riobard** [comment]
Closing now until 
https://github.com/shadowsocks/shadowsocks-org/issues/54 is resolved.
