### ISSUE TITLE
Support Win32

### ISSUE THREAD

**Issue by xmha97** [riobard/go-shadowsocks2#37]
Hello,
Please publish v0.1.0 for 32-bit windows.

**Comment by riobard** [comment]
Why are you still on 32-bit OS?

**Comment by xmha97** [comment]
I using 64-bit OS but in my office, there are many old computers (32-bit).

These old computers are responsive to the needs of employees, so they do not upgrade.
It is also expensive to upgrade computers.

The telegram is a popular Iranian messenger but has been censored by the Iranian government.

If the project continues to support 32bit OS, My friends can use the telegram.

Thanks.
(Sorry for my bad English)

**Comment by riobard** [comment]
I see. Please try the latest [v0.2.0 release](https://github.com/riobard/go-shadowsocks2/releases). However I have to point out that Go does not seem to work too well on 32-bit platforms and if there are any problems with the build, you're on your own to fix them. 

(Don't worry my Iranian friend, your English is very good :)

**Comment by xmha97** [comment]
> I see. Please try the latest [v0.2.0 release](https://github.com/riobard/go-shadowsocks2/releases). However I have to point out that Go does not seem to work too well on 32-bit platforms and if there are any problems with the build, you're on your own to fix them.
> 
> (Don't worry my Iranian friend, your English is very good :)

Thank you very much. ❤❤❤

**Comment by xmha97** [comment]
Dear @riobard 
[v0.2.0](https://github.com/riobard/go-shadowsocks2/releases) have a bug and I can't use it.
![Command Prompt](https://user-images.githubusercontent.com/23485114/74572453-64049f00-4f94-11ea-98f3-eb1f34b860b6.png)

**Comment by riobard** [comment]
See, this is why 32-bit OS sucks 😄 anyway here's a potential fix you could try https://github.com/riobard/go-shadowsocks2/releases/tag/v0.2.1 (I have no idea if it works)

**Comment by riobard** [comment]
Use this instead https://github.com/riobard/go-shadowsocks2/releases/tag/v0.2.2

**Comment by xmha97** [comment]
> See, this is why 32-bit OS sucks 😄 anyway here's a potential fix you could try https://github.com/riobard/go-shadowsocks2/releases/tag/v0.2.1 (I have no idea if it works)

v0.2.1 working fine
Thank you for your support.
![Telegram on Windows XP](https://user-images.githubusercontent.com/23485114/74595523-a9d66b80-5057-11ea-9497-2db5f394a7b7.PNG)

**Comment by xmha97** [comment]
> Use this instead https://github.com/riobard/go-shadowsocks2/releases/tag/v0.2.2

There is a problem releasing the v0.2.2
![7-Zip File Manager](https://user-images.githubusercontent.com/23485114/74595589-911a8580-5058-11ea-95b1-f3ab2aeedf7c.png)
In [shadowsocks2-win32.zip](https://github.com/riobard/go-shadowsocks2/releases/download/v0.2.2/shadowsocks2-win32.zip), there is an EXE file naming `shadowsocks2-win64.exe`!
Also in [shadowsocks2-win32.zip](https://github.com/riobard/go-shadowsocks2/releases/download/v0.2.2/shadowsocks2-win64.zip), there is an EXE file naming `shadowsocks2-win32.exe`!
But both files [shadowsocks2-win32.zip](https://github.com/riobard/go-shadowsocks2/releases/download/v0.2.2/shadowsocks2-win32.zip) and [shadowsocks2-win64.zip](https://github.com/riobard/go-shadowsocks2/releases/download/v0.2.2/shadowsocks2-win64.zip) are **64-bit** !!
![Windows Win32 Error](https://user-images.githubusercontent.com/23485114/74595847-f0c66000-505b-11ea-9a53-9ae6a3cb6ae3.png)
I think you should republish this release.
I hope you understand what I say.
Thanks.

**Comment by riobard** [comment]
Oops, there was a config error in the build script. Please try v0.2.3.

**Comment by xmha97** [comment]
> Oops, there was a config error in the build script. Please try v0.2.3.

Dear Rio
The EXE platform (32-bit or 64-bit) is right:
![image](https://user-images.githubusercontent.com/23485114/74615604-ae725100-5137-11ea-8acb-45bc3a0ebe22.png)
But can't use v0.2.3 on Windows XP and the problem persists!
![image](https://user-images.githubusercontent.com/23485114/74615101-cc898280-5132-11ea-974b-aa832908d11f.png)
Please repeat the steps you do to release v0.2.1 and use the previous release action.

**Comment by riobard** [comment]
WinXP? I think I know why… the previous build was done by an older version of Go (1.11 I think). The new build was done by recent version of Go 1.13. Go has completely dropped support for WinXP since 1.10. I'm afraid I cannot support ancient Go versions. You could fork this project and build on Go 1.10 instead, but there might be code that requires newer version of Go.

**Comment by xmha97** [comment]
I build from source using below command:
```
go get -u -v github.com/riobard/go-shadowsocks2
```
If you like, add this file to your release:
[go-shadowsocks2-winXP.zip](https://github.com/riobard/go-shadowsocks2/files/4211682/go-shadowsocks2-winXP.zip)
Thanks for your support.

**Comment by riobard** [comment]
Great if it still works on XP! 

Actually I'm going to stop releasing binaries from this repository, as it is meant to be more cutting-edge and experimental. People wanting release binaries should use the stable fork at https://github.com/shadowsocks/go-shadowsocks2/ instead.
