### ISSUE TITLE
重写cow

### ISSUE THREAD

**Issue by bigtan** [riobard/go-shadowsocks2#6]
https://github.com/cyfdecyf/cow 是一个提供http协议，并且能自动进行分流的客户端。由于目前shadowsocks-go作者并没有继续进行维护，而cow的shadowsocks协议部分是基于shadowsocks-go。所以，作者有没有重写cow客户端的意愿。

我大致调研了一下，https://github.com/golang/net/blob/master/proxy/per_host.go 提供了代理分流的一些简单的范例，我对网络编程不是非常熟悉，不知道作者有没有想法协助一下。

我的设想是大概在前端提供http代理，根据配置文件中的规则进行分流，后端使用go-shadowsocks2。

**Comment by riobard** [comment]
直接用 cow 有什么问题？

**Comment by bigtan** [comment]
不支持新的加密方式

**Comment by riobard** [comment]
可以直接去 cow 那里提个 issue，让他们改用 go-ss2 就可以了。

**Comment by bigtan** [comment]
我用privoxy+go-ss2代替了cow，效果还好一点。
