### ISSUE TITLE
不需要obfs吗？

### ISSUE THREAD

**Issue by nkta3m** [riobard/go-shadowsocks2#7]
我下载了64位的，已经成功连接了我的ss-server，有一个疑问，我的server设置了plugin-obfs，我使用以下命令：
go-shadowsocks2 -c ss://CHACHA20_IETF:password@[server_address]:8488 -verbose -socks :1080 
这样配合Proxy-SwitchyOmega就成功了，为什么不需要plugin呢？

**Comment by riobard** [comment]
要么插件未生效，要么 server 是兼容模式。

**Comment by nkta3m** [comment]
那么go-shadowsocks如何使用plugin呢？

**Comment by riobard** [comment]
暂未支持。可以先手动启动 plugin 配置一下，稍微麻烦点

**Comment by nkta3m** [comment]
明白了，谢谢
