### ISSUE TITLE
Daemon mode? 

### ISSUE THREAD

**Issue by x0r2d2** [riobard/go-shadowsocks2#9]
How to start go-ss2 in daemon mode?

**Comment by riobard** [comment]
Daemonization should be handled by your OS, e.g. supervisor/systemd/upstart/launchd.

**Comment by x0r2d2** [comment]
I am not a master of Linux, what I need to do to make it real?

**Comment by riobard** [comment]
Most modern Linux distro use systemd now. Google "systemd service file".

**Comment by bigtan** [comment]
```
[Unit]
Description=Shadowsocks Server
After=network.target

[Service]
ExecStart=/usr/bin/ss-server -s ss://AEAD_CHACHA20_POLY1305:xxxxxxxxx@:xxxx
User=nobody
Group=nogroup

[Install]
WantedBy=multi-user.target
```

refer to https://github.com/shadowsocks/shadowsocks-go/issues/141
